# Quarkus will choose application.yaml over application.properties.
quarkus:
  package:
    jar:
      type: uber-jar
  application:
    name: "pnc-tracker"
  container-image:
    builder: jib
    registry: quay.io
    group: rh-newcastle-devel
    name: pnc-tracker
    additional-tags: latest
  hibernate-orm:
    schema-management:
      strategy: validate
  datasource:
    db-kind: ${QUARKUS_DATASOURCE:postgresql}
    jdbc:
      url: ${QUARKUS_DATASOURCE_URL:}
      username: ${QUARKUS_DATASOURCE_USERNAME:}
      password: ${QUARKUS_DATASOURCE_PASSWORD:}
      # params recommended for stability:
      min-size: 2
      max-size: 10
      acquisition-timeout: 5s
  index-dependency:
    pnc-api:
      group-id: org.jboss.pnc
      artifact-id: pnc-api
  swagger-ui:
    always-include: true

"%dev":
  quarkus:
    kubernetes-config:
      enabled: false
    log:
      level: INFO
      category:
        "org.jboss.pnc.tracker":
          level: DEBUG
      console:
        enable: true
      file:
        enable: true
        path: "/tmp/pnc-tracker.log"
        format: "%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
        rotation:
          max-backup-index: 5
          max-file-size: 10M

"%test":
  quarkus:
    log:
      level: INFO
      category:
        "org.jboss.pnc.tracker":
          level: DEBUG
      console:
        enable: true
